FIND_PATH(GLOG_INCLUDE_DIR glog/logging.h)
FIND_LIBRARY(GLOG_LIBRARIES NAMES glog)


IF (GLOG_LIBRARIES AND GLOG_INCLUDE_DIR)
   SET(GLOG_FOUND TRUE)
ENDIF (GLOG_LIBRARIES AND GLOG_INCLUDE_DIR)

IF (GLOG_FOUND)
    IF (NOT GLOG_FIND_QUIETLY)
       MESSAGE(STATUS "Found GLOG: ${GLOG_LIBRARIES}")
    ENDIF(NOT GLOG_FIND_QUIETLY)
ELSE (GLOG_FOUND)
    IF (GLOG_FIND_REQUIRED)
       MESSAGE(FATAL_ERROR "Could not find GLOG library: ${GLOG_LIBRARIES}, ${GLOG_INCLUDE_DIR}")
    ENDIF (GLOG_FIND_REQUIRED)
ENDIF (GLOG_FOUND)

MARK_AS_ADVANCED(GLOG_LIBRARIES GLOG_INCLUDE_DIR)