FIND_PATH(GTEST_INCLUDE_DIR gtest/gtest.h)
FIND_LIBRARY(GTEST_LIBRARIES NAMES gtest)


IF (GTEST_LIBRARIES AND GTEST_INCLUDE_DIR)
   SET(GTEST_FOUND TRUE)
ENDIF (GTEST_LIBRARIES AND GTEST_INCLUDE_DIR)

IF (GTEST_FOUND)
    IF (NOT GTEST_FIND_QUIETLY)
       MESSAGE(STATUS "Found GTEST: ${GTEST_LIBRARIES}")
    ENDIF(NOT GTEST_FIND_QUIETLY)
ELSE (GTEST_FOUND)
    IF (GTEST_FIND_REQUIRED)
       MESSAGE(FATAL_ERROR "Could not find GTEST library: ${GTEST_LIBRARIES}, ${GTEST_INCLUDE_DIR}")
    ENDIF (GTEST_FIND_REQUIRED)
ENDIF (GTEST_FOUND)

MARK_AS_ADVANCED(GTEST_LIBRARIES GTEST_INCLUDE_DIR)

