FIND_PATH(GLEW_INCLUDE_DIR GL/glew.h)
FIND_LIBRARY(GLEW_LIBRARIES NAMES GLEW)


IF (GLEW_LIBRARIES AND GLEW_INCLUDE_DIR)
   SET(GLEW_FOUND TRUE)
ENDIF ()

IF (GLEW_FOUND)
    IF (NOT GLEW_FIND_QUIETLY)
       MESSAGE(STATUS "Found GLEW: ${GLEW_LIBRARIES}")
    ENDIF()
ELSE (GLEW_FOUND)
    IF (GLEW_FIND_REQUIRED)
       MESSAGE(FATAL_ERROR "Could not find GLEW library: ${GLEW_LIBRARIES}, ${GLEW_INCLUDE_DIR}")
    ENDIF ()
ENDIF ()

MARK_AS_ADVANCED(GLEW_LIBRARIES GLEW_INCLUDE_DIR)
