FIND_PATH(GPROFILER_INCLUDE_DIR google/profiler.h)
FIND_LIBRARY(GPROFILER_LIBRARIES NAMES profiler)


IF (GPROFILER_LIBRARIES AND GPROFILER_INCLUDE_DIR)
   SET(GPROFILER_FOUND TRUE)
ENDIF (GPROFILER_LIBRARIES AND GPROFILER_INCLUDE_DIR)

IF (GPROFILER_FOUND)
    IF (NOT GPROFILER_FIND_QUIETLY)
       MESSAGE(STATUS "Found GPROFILER: ${GPROFILER_LIBRARIES}")
    ENDIF(NOT GPROFILER_FIND_QUIETLY)
ELSE (GPROFILER_FOUND)
    IF (GPROFILER_FIND_REQUIRED)
       MESSAGE(FATAL_ERROR "Could not find GPROFILER library: ${GPROFILER_LIBRARIES}, ${GPROFILER_INCLUDE_DIR}")
    ENDIF (GPROFILER_FIND_REQUIRED)
ENDIF (GPROFILER_FOUND)

MARK_AS_ADVANCED(GPROFILER_LIBRARIES GPROFILER_INCLUDE_DIR)

